---
# ================================
#       Server Configuration
# ================================

# The folder where persistent data will be stored
srv_data: /data

# The server domain
srv_domain: arkham.asylum

# The server organization name
srv_org: Arkham Asylum

# The root folder where all the services will be installed
srv_root: /srv

# ================================
#        Mail Configuration
# ================================

# The administrator email address
email_administrator: admin@{{ srv_domain }}

# The no-reply email address
email_noreply: noreply@{{ srv_domain }}

# ================================
#       Docker Configuration
# ================================

# The default Docker attributes
compose_defaults:
  logging: { driver: "json-file", options: { max-size: "10m", max-file: "1" } }
  restart: unless-stopped

# The default network CIDRs
compose_networks:
  proxy:    172.16.100.0/24
  ldap:     172.16.110.0/24
  sso:      172.16.120.0/24
  database: 172.16.130.0/24
  cache:    172.16.130.0/24

# ================================
#      Services Configuration
# ================================

# --- | Adminer
# Adminer is a full-featured database management tool written in PHP. Conversely to phpMyAdmin,
# it consist of a single file ready to deploy to the target server.
# Website: https://www.adminer.org/

# The Adminer domain (needed if using proxy)
adminer_domain: "{{ srv_domain }}"

# The Adminer path (needed if using proxy)
adminer_path: /db

# The Adminer port (needed if not using proxy)
adminer_port: 8080

# The Adminer theme
adminer_theme: hydra

# --- | Authelia
# Authelia is an open-source authentication and authorization server providing 2-factor authentication and single sign-on (SSO)
# for your applications via a web portal.
# Website: https://www.authelia.com/

# The Authelia admin password
authelia_admin_pass: changeme!admin

# The Authelia domain
authelia_domain: "{{ srv_domain }}"

# The Authelia path
authelia_path: /auth

# The Authelia default policy for every in-scope resource
authelia_policy: one_factor

# The Authelia clients
authelia_clients:
  just-an-example-service:
    secret: changeme!oidc!secret!gitea
    redirects: [ "https://{{ srv_domain }}/user/oauth2/authelia/callback" ]

# The Authelia JWT secret
authelia_secret_jwt: changeme!oidc!secret!jwt

# The Authelia Session secret
authelia_secret_session: changeme!oidc!secret!session

# The Authelia Storage secret
authelia_secret_storage: changeme!oidc!secret!storage

# --- | Error Pages
# Error Pages is a simple, standalone, self-hosted, extensible, lightweight and easy-to-use error pages for your web applications.
# Website: https://tarampampam.github.io/error-pages/

# If detailed Error Pages should be shown
errorpages_details: true

# The Error Pages port (needed if not using proxy)
errorpages_port: 8080

# The Error Pages theme (ghost, l7-light, l7-dark, shuffle, noise, hacker-terminal, cats, lost-in-space, app-down, connection, matrix, orient)
errorpages_theme: l7-dark

# --- | Homepage
# Homepage is a simple, standalone, self-hosted, extensible, lightweight and easy-to-use dashboard to organize your web applications.
# Website: https://gethomepage.org/

# The Homepage domain (needed if using proxy)
homepage_domain: "{{ srv_domain }}"

# The Homepage port (needed if not using proxy)
homepage_port: 3000

# The Homepage theme (dark, light)
homepage_theme: light

# The Homepage color scheme
homepage_color: white

# The Homepage header style (underlined, boxed, clean, boxedWidgets)
homepage_header: underlined

# --- | OpenLDAP
# OpenLDAP is a free, open-source implementation of the Lightweight Directory Access Protocol (LDAP) developed by the OpenLDAP
# Project. It is released under its own BSD-style license called the OpenLDAP Public License.
# Website: https://www.openldap.org/

# The OpenLDAP admin password
ldap_admin_pass: changeme!admin

# The OpenLDAP config password
ldap_config_pass: changeme!config

# The OpenLDAP read-only user
ldap_read_user: readonly

# The OpenLDAP read-only user password
ldap_read_pass: changeme!readonly

# --- | MariaDB
# MariaDB is a community-developed, commercially supported fork of the MySQL relational database management system, intended to remain
# free and open-source software under the GNU General Public License.
# Website: https://mariadb.org/

# The MariaDB root password
mariadb_admin_pass: changeme!root

# --- | phpLDAPadmin
# phpLDAPadmin is a web-based LDAP client. It provides easy, anywhere-accessible, multi-language administration for your LDAP server.
# Website: https://www.phpldapadmin.net/

# The phpLDAPadmin domain (needed if using proxy)
phpldapadmin_domain: "{{ srv_domain }}"

# The phpLDAPadmin path
phpldapadmin_path: /ldap

# The phpLDAPadmin port (needed if not using proxy)
phpldapadmin_port: 8081

# --- | Traefik
# Traefik is an open-source Edge Router that makes publishing your services a fun and easy experience. It receives requests on behalf of
# your system and finds out which components are responsible for handling them.
# Website: https://traefik.io/

# Generate staging certificates
traefik_dev: false

# Enable internal services TLS (DNS challenge)
traefik_internal: false

# DNS challenge provider
traefik_provider: "{{ 'cloudflare' if traefik_internal else '' }}"

# --- | WatchTower
# Watchtower is a process for automating Docker container base image updates. It is a process that runs in a container
# in your environment and automatically updates your running containers when it detects that their base images have been updated.
# Website: https://containrrr.dev/watchtower/

watchtower_schedule: "0 0 4 * * *"

# ================================
#     API Tokens Configuration
# ================================

# Cloudflare API Token
token_cloudflare: ''