---
- name: Ensure that at least one service is defined
  ansible.builtin.fail:
    msg: "At least one service must be defined using the 'services' variable."
  when: services|length == 0

- name: Ensure that the state is correctly set
  ansible.builtin.fail:
    msg: "'state' variable must be one of [running, present, stopped, absent]."
  when: state not in ['running', 'present', 'stopped', 'absent']