---
http:
  middlewares:
    # --- | Compress the response body
    compression:
      compress:
        minResponseBodyBytes: 1024
        excludedContentTypes:
          - 'text/event-stream'

    # --- | Custom error pages (errorpages service is required)
    errors:
      errors:
        status:
          - '400-599'
        service: 'errorpages@docker'
        query: '/{status}.html'

    # --- | Custom response headers (some little jokes and puns)
    jokes:
      headers:
        customResponseHeaders:
          Server: 'Nokia 3310'
          X-Clacks-Overhead: 'GNU Kike Fontan'
          X-mas: 'Ho ho ho!'
          X-Men: 'Wolverine and Deadpool'
          X-NaNaNaNaNaNaNaNa: 'Batman!'
          X-PoweredBy: 'Pumas, unicorns and rainbows'
          X-Rays: 'Mr. Rontgen'

    # --- | Strict Transport Security header
    hsts:
      headers:
        forceSTSHeader: true
        stsPreload: true
        stsSeconds: 315360000
        stsIncludeSubdomains: true

    # --- | Chain: Redirect to HTTPS + Force HSTS
    https-only:
      chain:
        middlewares:
          - 'https-redirect@file'
          - 'hsts@file'

    # --- | Redirect to HTTPS
    https-redirect:
      redirectScheme:
        port: 443
        scheme: 'https'
        permanent: true

    # --- | Chain: Security headers + Redirect to HTTPS + Force HSTS
    security:
      chain:
        middlewares:
          - 'security-headers@file'
          - 'https-only@file'

    # --- | Security headers
    security-headers:
      headers:
        contentTypeNosniff: true          # Prevents browsers from trying to guess a MIME type
        browserXssFilter: true            # Prevents reflected XSS attacks
        contentSecurityPolicy: |          # Defines the Content Security Policy
          default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; font-src 'self'; connect-src 'self'; object-src 'none'; frame-ancestors 'self'; form-action 'self'; base-uri 'self';
        referrerPolicy: 'no-referrer'     # Hide the Referer header
        isDevelopment: false              # Always act as if the app is in production
        customResponseHeaders:
          X-Frame-Options: 'SAMEORIGIN'   # Prevents clickjacking attacks
          X-Robots-Tag: |                 # Prevents search engines from indexing the site
            noindex, nofollow, nosnippet, noarchive, notranslate, noimageindex, nositelinkssearchbox

    # --- | Private IP only allow list
    internal:
      ipAllowList:
        sourceRange:
          - '10.0.0.0/8'
          - '127.0.0.1/32'
          - '172.16.0.0/12'
          - '192.168.0.0/16'
          - 'fc00::/7'
...
