---
- name: Install Docker on Alpine
  when: ansible_distribution|lower == 'alpine'
  block:
    - name: Install Docker dependencies
      ansible.builtin.package: name=openrc state=present

    - name: Install 'docker' package and plugins
      ansible.builtin.package: name={{ package }} state=present
      loop_control: { loop_var: package }
      loop:
        - docker
        - docker-cli-compose

- name: Install Docker on Debian/Ubuntu
  when: ansible_distribution|lower in ['debian','ubuntu']
  ansible.builtin.fail: msg="#TODO Docker installation on Debian/Ubuntu"


- name: Install Docker on CentOS/Fedora/RedHat
  when: ansible_distribution|lower in ['centos','fedora','redhat']
  ansible.builtin.fail: msg="#TODO Docker installation on CentOS/Fedora/RedHat"


- name: Enable and start Docker
  ansible.builtin.service: name=docker enabled=true state=started