---
- name: Update Debian/Ubuntu
  when: ansible_distribution|lower in ['debian','ubuntu']
  block:
    - name: Update 'apt' packages
      ansible.builtin.apt: update_cache=true upgrade=full cache_valid_time=3600

    - name: Check if reboot is required
      ansible.builtin.stat: path=/var/run/reboot-required
      register: reboot_required


- name: Update CentOS/Fedora/RedHat
  when: ansible_distribution|lower in ['centos','fedora','redhat']
  block:
    - name: Update 'dnf' packages
      ansible.builtin.dnf: name=* state=latest update_only=true

    - name: Install 'dnf-utils' package
      ansible.builtin.dnf: name=dnf-utils state=present
    
    - name: Check if reboot is required
      ansible.builtin.command: needs-restarting -r
      register: reboot_required
      ignore_errors: true
      changed_when: reboot_required.rc != 0


- name: Update Alpine
  when: ansible_distribution|lower == 'alpine'
  block:
    - name: Update 'apk' packages
      community.general.apk: update_cache=true upgrade=true


- name: Reboot if required
  ansible.builtin.reboot: msg="Rebooting the system to apply updates"
  when: reboot_required is defined and reboot_required.rc|default(1) == 0
