---
- name: "Check that the 'public' newtork exists"
  community.docker.docker_network_info:
    name: 'public'
  register: 'docker_network_public'

- name: 'Check that the Dozzler domain is defined'
  ansible.builtin.fail:
    msg: "The Dozzler domain (dozzler_domain) is required when using the public network."
  when: 'docker_network_public.exists and dozzler_domain|trim|length == 0'
...
