---
- name: Create the ErrorPages configuration folder
  ansible.builtin.file: state=directory path="{{ srv_root }}/errorpages" mode=0700 access_time=preserve modification_time=preserve

- name: Check if the 'proxy' network exists
  community.docker.docker_network_info: name=proxy
  register: docker_network_proxy

- name: Create the ErrorPages compose file
  changed_when: false
  ansible.builtin.copy:
    dest: "{{ srv_root }}/errorpages/docker-compose.yml"
    mode: "0400"
    content: |
      ---
      x-defaults: &defaults
        {{ compose_defaults|to_yaml|trim|indent(2) }}
      {% if docker_network_proxy.exists|bool %}

      networks:
        proxy: { external: true }
      {% endif %}

      services:
        errorpages:
          <<: *defaults
          container_name: errorpages
          hostname: errorpages
          image: tarampampam/error-pages:latest
      {% if docker_network_proxy.exists|bool %}
          networks:
            - proxy
      {% else %}
          ports: ["{{ errorpages_port }}:8080/tcp"]
      {% endif %}
          security_opt: [no-new-privileges]
          healthcheck:
            test: [ CMD, "/bin/error-pages", "--log-json", "healthcheck" ]
            start_period: 5s
            interval: 60s
            timeout: 10s
            retries: 3
          environment:
            TEMPLATE_NAME: "{{ errorpages_theme }}"
            SHOW_DETAILS: "{{ errorpages_details }}"
          labels:
            com.centurylinklabs.watchtower.enable: true
            homepage.name: ErrorPages
            homepage.group: Services
            homepage.description: Custom error pages
            homepage.icon: /icons/errorpages.png
      {% if docker_network_proxy.exists|bool %}
            traefik.enable: true
            traefik.http.routers.errorpages.rule: Host(`{host:.+}`)
            traefik.http.routers.errorpages.priority: 10
            traefik.http.routers.errorpages.entrypoints: https
            traefik.http.routers.errorpages.service: errorpages
            traefik.http.services.errorpages.loadbalancer.server.port: 8080
      {% endif %}

- name: Deploy ErrorPages service
  community.docker.docker_compose_v2: project_src="{{ srv_root }}/errorpages" remove_orphans=true