---
- name: 'Check that domain is defined'
  ansible.builtin.fail:
    msg: "The domain (vaultwarden_domain) is required"
  when: 'vaultwarden_domain|trim|length == 0'

- name: "Check if the 'public' network exists"
  community.docker.docker_network_info:
    name: 'public'
  register: 'docker_network_public'

- name: "Ensure that the 'public' network exists"
  ansible.builtin.fail:
    msg: "The 'public' network does not exist. It may indicate that the Traefik service is not running."
  when: 'not docker_network_public.exists'
...
